site_title = "My Arxiv Daily"
limit_days = 7
cache_url = "https://yueyin27.github.io/MyArxivDaily/cache.json"

[[sources]]
limit = 100
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 100
category = "cs.LG"
title = "Machine Learning"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
